// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';
import svelte from '@astrojs/svelte';

// The production origin. Override with SITE_URL for preview deploys if desired.
const site = process.env.SITE_URL ?? 'https://wecanjustbuildthings.dev';

// Plausible is opt-in: only injected when PLAUSIBLE_DOMAIN is set, so local dev
// and forks stay analytics-free by default (privacy-first, see /privacy).
const plausibleDomain = process.env.PLAUSIBLE_DOMAIN;
const plausibleHead = plausibleDomain
  ? [
      {
        tag: /** @type {const} */ ('script'),
        attrs: {
          defer: true,
          'data-domain': plausibleDomain,
          src: 'https://plausible.io/js/script.js',
        },
      },
    ]
  : [];

export default defineConfig({
  site,
  output: 'static',
  trailingSlash: 'ignore',
  integrations: [
    starlight({
      title: 'We Can Just Build Things',
      tagline: 'Build the tools your community needs — freedom tech, made with an AI agent, grounded in a verified catalog you can trust.',
      description:
        'Liberation tech for builders: a verified catalog of Nostr, AT Protocol, and freedom-tech tools, a guided flow from idea to shipped, and safeguards that keep what you build clean — so organizers, nonprofits, and collectives can ship production-grade, privacy-respecting software with an AI agent like Goose or Claude Code.',
      logo: { src: './src/assets/logo.svg', alt: 'We Can Just Build Things' },
      favicon: '/favicon.svg',
      head: [
        ...plausibleHead,
        {
          tag: 'meta',
          attrs: { property: 'og:image', content: `${site}/og.png` },
        },
        {
          tag: 'meta',
          attrs: { name: 'twitter:card', content: 'summary_large_image' },
        },
      ],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/martinmontero/wecanjustbuildthings.dev',
        },
      ],
      editLink: {
        baseUrl: 'https://github.com/martinmontero/wecanjustbuildthings.dev/edit/main/',
      },
      lastUpdated: true,
      customCss: ['./src/styles/theme.css'],
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'What this is', link: '/start/' },
            { label: 'Why not just use Goose?', link: '/start/vs-harness/' },
            { label: 'Quickstart with an agent', link: '/start/quickstart/' },
          ],
        },
        {
          label: 'Tools',
          items: [
            { label: 'Build Studio', link: '/build/', badge: { text: 'new', variant: 'tip' } },
            { label: 'Check a dependency', link: '/check/' },
          ],
        },
        {
          label: 'Socratic Intent (the method)',
          items: [{ autogenerate: { directory: 'method' } }],
        },
        {
          label: 'The build flow (PIE)',
          items: [{ autogenerate: { directory: 'pie' } }],
        },
        {
          // The catalog has >1,000 entries — browse via the overview + search
          // rather than an autogenerated sidebar (which would bloat every page).
          label: 'Catalog',
          items: [{ label: 'Browse the catalog', link: '/catalog/' }],
        },
        {
          label: 'Recipes',
          items: [{ autogenerate: { directory: 'recipes' } }],
        },
        {
          label: 'Policies & trust',
          items: [
            { label: 'The exclusion policy', link: '/policies/' },
            { label: 'How enforcement works', link: '/policies/enforcement/' },
            { label: 'Privacy', link: '/privacy/' },
            { label: 'Security', link: '/security/' },
          ],
        },
        {
          label: 'Contribute',
          items: [
            { label: 'Add a tool', link: '/contribute/' },
            { label: 'About & maintenance', link: '/about/' },
          ],
        },
      ],
    }),
    sitemap(),
    svelte(),
  ],
});
