/**
 * Generate the Material 3 colour token layer from a single seed (the project's
 * purple) using Material Color Utilities (MCU, Apache-2.0) — per the Design Field
 * Manual §7.1 ("generate the colour set with MCU from a single seed; it emits
 * accessible tonal palettes automatically").
 *
 * Emits src/styles/colors.generated.css with the full --md-sys-color-* role set
 * for light + dark, plus the seed-derived Starlight accent tones. Build-time only
 * and the output is committed, so MCU itself never ships to the browser.
 *
 * Run: npm run gen:colors
 */
import { writeFileSync } from 'node:fs';
import { argbFromHex, hexFromArgb, themeFromSourceColor } from '@material/material-color-utilities';

const SEED = '#6d3bd6'; // freedom-tech / Nostr-lineage purple
const theme = themeFromSourceColor(argbFromHex(SEED));

/** MCU Scheme → "--md-sys-color-<kebab>: #hex;" lines. */
function roleVars(scheme: { toJSON(): Record<string, number> }): string {
  return Object.entries(scheme.toJSON())
    .map(([k, argb]) => `  --md-sys-color-${k.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}: ${hexFromArgb(argb)};`)
    .join('\n');
}

const primary = theme.palettes.primary;
const tone = (n: number) => hexFromArgb(primary.tone(n));

/* MCU 0.4's Scheme predates M3's surface-container roles, so derive them from the
   neutral palette using M3's documented tone mapping (m3.material.io). Without
   these, every `--md-sys-color-surface-container*` reference is undefined — CSS
   silently drops the background and SVG `fill` falls back to black. */
const neutral = theme.palettes.neutral;
const nt = (n: number) => hexFromArgb(neutral.tone(n));
function surfaceContainers(map: Record<string, number>): string {
  return Object.entries(map)
    .map(([role, t]) => `  --md-sys-color-${role}: ${nt(t)};`)
    .join('\n');
}
const DARK_SURFACES = {
  'surface-dim': 6, 'surface-bright': 24,
  'surface-container-lowest': 4, 'surface-container-low': 10,
  'surface-container': 12, 'surface-container-high': 17, 'surface-container-highest': 22,
};
const LIGHT_SURFACES = {
  'surface-dim': 87, 'surface-bright': 98,
  'surface-container-lowest': 100, 'surface-container-low': 96,
  'surface-container': 94, 'surface-container-high': 92, 'surface-container-highest': 90,
};

const css = `/* GENERATED by scripts/gen-theme-colors.ts — DO NOT EDIT BY HAND.
   Material 3 colour tokens from seed ${SEED} via Material Color Utilities.
   Regenerate with \`npm run gen:colors\`.
   :root = dark theme; [data-theme='light'] = light theme. */

:root {
${roleVars(theme.schemes.dark)}

  /* M3 surface-container tonal levels (neutral palette; not in MCU 0.4's Scheme). */
${surfaceContainers(DARK_SURFACES)}

  /* Seed-derived Starlight accent (dark): low-emphasis bg / mid / high-contrast. */
  --sl-color-accent-low: ${tone(20)};
  --sl-color-accent: ${tone(72)};
  --sl-color-accent-high: ${tone(90)};
  /* Text on a filled accent surface. Dark accent is light, so text must be dark. */
  --wcb-on-accent: ${tone(10)};
}

:root[data-theme='light'] {
${roleVars(theme.schemes.light)}

  /* M3 surface-container tonal levels (neutral palette; not in MCU 0.4's Scheme). */
${surfaceContainers(LIGHT_SURFACES)}

  /* Seed-derived Starlight accent (light). */
  --sl-color-accent-low: ${tone(90)};
  --sl-color-accent: ${tone(40)};
  --sl-color-accent-high: ${tone(20)};
  /* Light accent is mid-dark, so white text pairs accessibly (M3 primary/on-primary). */
  --wcb-on-accent: #ffffff;
}
`;

writeFileSync('src/styles/colors.generated.css', css);
console.log('Wrote src/styles/colors.generated.css from seed', SEED);
console.log('dark accent  20/72/90:', tone(20), tone(72), tone(90));
console.log('light accent 90/40/20:', tone(90), tone(40), tone(20));
